### ISSUE TITLE
Map export without excel files has circles without names

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#74] opened 2022-04-30 09:21 UTC
If one uses the tool and creates only the maps without the excel spreadsheet, the route is drawn fine. However, the walktable selected points are only drawn as circles, without the name written beside them.

**Comment by wp99cp** [comment] 2022-04-30 10:16
We should ask ourselves if this is the intended behaviour, or if we should treat this as a bug.

Here's what I propose: We add an additional option to control whether the points on the map have a name or not. This option is then independent of the Excel inclusion and can be controlled in the "Einstellungen zur Karte" tab of the UI.

**Comment by maede97** [comment] 2022-04-30 10:34
I think the option should more be in the sense of wheter to add the points to the map or not. If you do not want the names, adding the points does not make sense (in my opinion).

Furthermore, if we want to upgrade the tool later to let the user move points & select others, this will be obsolete I guess. But for the moment, I like the idea of adding a simple option to the map settings.

**Comment by wp99cp** [comment] 2022-06-08 11:47
fixed with 268fcc4c03e5d7196231d914767796840d4d6a40

**Closed** 2022-08-05 19:41 UTC
